import os
import json
import plotly.graph_objects as go
import streamlit as st
import time
import json

from superAgent import SuperAgent
from backend import dispatch_call, fetch_conversation_history, fetch_metrics, stop_worker

def extract_latency_metrics(phone):
    import numpy as np
    metrics_dir = os.path.join(os.path.dirname(__file__), '..', 'log_metrics')
    pattern = f"+91{phone}_CallMetrics_"
    files = [f for f in os.listdir(metrics_dir) if f.startswith(pattern) and f.endswith('.txt')]
    files.sort(reverse=True)
    if not files:
        return None
    with open(os.path.join(metrics_dir, files[0]), "r", encoding="utf-8") as f:
        metrics = json.load(f)

    # EOU: end_of_utterance_delay
    eou_metrics = metrics.get("EOU_METRICS", [])
    eou_eoud = [m.get("end_of_utterance_delay", 0) for m in eou_metrics if "end_of_utterance_delay" in m]
    avg_eou = np.mean(eou_eoud) if eou_eoud else 0

    # LLM: ttft
    llm_metrics = metrics.get("LLM_METRICS", [])
    llm_ttft = [m.get("ttft", 0) for m in llm_metrics if "ttft" in m]
    avg_llm_ttft = np.mean(llm_ttft) if llm_ttft else 0

    # TTS: ttfb
    tts_metrics = metrics.get("TTS_METRICS", [])
    tts_ttfb = [m.get("ttfb", 0) for m in tts_metrics if "ttfb" in m]
    avg_tts_ttfb = np.mean(tts_ttfb) if tts_ttfb else 0

    # Total latency as per your formula
    total_latency = avg_eou + avg_llm_ttft + avg_tts_ttfb

    return {
        "EOU": avg_eou,
        "LLM": avg_llm_ttft,
        "TTS": avg_tts_ttfb,
        "Total": total_latency
    }


st.set_page_config(page_title="PredixionAI Loan Collection Agent", layout="wide")
st.title("📞 Live Call Session")

user = st.session_state.get("selected_user")
if not user:
    st.warning("No user selected. Please start from the main app.")
    st.stop()

st.subheader(f"Active Call with {user['Name']}")

# Initialize transcript in session state
if 'full_transcript' not in st.session_state:
    st.session_state.full_transcript = []

# Display borrower metadata
with st.expander("📋 Borrower Details"):
    for key, value in user.items():
       if key != "Preference":
        # print(f"Key: {key}, Value: {value}")  # Debugging line
        st.markdown(f"**{key}:** {value}")

#Launch call only once
if not st.session_state.get("call_active"):
    st.session_state["call_active"] = True
    dispatch_call(user["Phone"])

tab1 , tab2,tab3 = st.tabs(["Summary", "Metrics","Conversation History"])



with tab1:
    
    # ------------------------------------- Prints the summary generated by LLM ------------------------------------
    if st.button("Show Call Summary"):
        agent = SuperAgent()
        summary_whatsapp, summary_call = agent.generate_summary(user["Phone"])
        st.markdown("#### 📋 Call Summary")
        st.info(summary_call)

with tab2:

    #---------------------Metrics Visualization Donut Graph -----------------------------
    # st.markdown("### 📊Metrics")
    latency_metrics = extract_latency_metrics(user["Phone"])
    if latency_metrics:
        # Prepare values
        eou_ms = int(latency_metrics['EOU'] * 1000)
        llm_ms = int(latency_metrics['LLM'] * 1000)
        tts_ms = int(latency_metrics['TTS'] * 1000)
        total_ms = int(latency_metrics['Total'] * 1000)

        col1, col2, col3, col4 = st.columns([0.5,0.5,0.5,1.5])

        with col1:
            fig = go.Figure(data=[go.Pie(
                labels=['EOU', ''],
                values=[eou_ms, max(1, total_ms - eou_ms)],
                hole=0.7,
                marker_colors=['#4285F4', '#E8EAED'],
                textinfo='none'
            )])
            fig.update_layout(
                showlegend=False,
                margin=dict(l=0, r=0, t=0, b=0),
                annotations=[dict(text=f"<b>{eou_ms}ms</b><br>EOU", x=0.5, y=0.5, font_size=16, showarrow=False)]
            )
            st.plotly_chart(fig, use_container_width=True)

        with col2:
            fig = go.Figure(data=[go.Pie(
                labels=['LLM', ''],
                values=[llm_ms, max(1, total_ms - llm_ms)],
                hole=0.7,
                marker_colors=['#A259D9', '#E8EAED'],
                textinfo='none'
            )])
            fig.update_layout(
                showlegend=False,
                margin=dict(l=0, r=0, t=0, b=0),
                annotations=[dict(text=f"<b>{llm_ms}ms</b><br>LLM", x=0.5, y=0.5, font_size=16, showarrow=False)]
            )
            st.plotly_chart(fig, use_container_width=True)

        with col3:
            fig = go.Figure(data=[go.Pie(
                labels=['TTS', ''],
                values=[tts_ms, max(1, total_ms - tts_ms)],
                hole=0.7,
                marker_colors=['#34A853', '#E8EAED'],
                textinfo='none'
            )])
            fig.update_layout(
                showlegend=False,
                margin=dict(l=0, r=0, t=0, b=0),
                annotations=[dict(text=f"<b>{tts_ms}ms</b><br>TTS", x=0.5, y=0.5, font_size=16, showarrow=False)]
            )
            st.plotly_chart(fig, use_container_width=True)

        # Total Latency and Status
        with col4:
            st.markdown("<h2>Total Latency</h2>", unsafe_allow_html=True)
            st.markdown(f"<h4 style='color:#F4B400'>{total_ms}ms</h4>", unsafe_allow_html=True)
            if total_ms < 500:
                st.success("Good")
            else:
                st.warning("High Latency")
        
        # if st.session_state.get("call_active"):
        #     stop_worker()
        #     st.session_state["call_active"] = False
    else:
        st.info("No metrics available.")




with tab3:
     
    history = fetch_conversation_history(user["Phone"])
    convo_displayed = False

    if history:
        # Get the most recent conversation (last item in call_transcripts)
        recent_convo = history[-1] if isinstance(history, list) else history
        
        if isinstance(recent_convo, list):
            for msg in recent_convo:
                if isinstance(msg, dict):
                    name = next((k for k in msg.keys() if k != "timestamp"), "Unknown")
                    text = msg.get(name, "")
                    st.markdown(f"**{name}:** {text}")
        else:
            st.info("Conversation format not recognized")
        
        convo_displayed= True
    else:
        st.info("No conversation history found for this number.")
    
    if convo_displayed:
        stop_worker()
